Repository scenerygraphics/sciview, pull requests merged in 2024-04, with the labels that each got.

#571 Bump scenery to 0.11.0
  build.gradle.kts
  gradle.properties
  src/main/kotlin/sc/iview/commands/add/AddOrientationCompass.kt
Labels: build-system

#577 Deploy to Fiji
  bootstrap-fiji.sh
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/sciview/fiji.gradle.kts
  buildSrc/src/main/kotlin/sciview/populateFiji.gradle.kts
  gradle.properties
  sciview_deploy.sh
  sciview_deploy_unstable.sh
  src/main/java/sc/iview/commands/help/About.java
  src/main/kotlin/sc/iview/SciView.kt
  src/main/kotlin/sc/iview/SplashLabel.kt
  upload-site-simple.sh
Labels: enhancement

#580 Bump scenery 0.11.2
  build.gradle.kts
Labels: build-system

#562 Enable dependabot version updates
  .github/dependabot.yml
Labels: build-system

#587 Fix: recursive delete calls no longer use activePublish
  src/main/kotlin/sc/iview/SciView.kt
Labels: bugfix, prague-hackathon-2024
